### ISSUE TITLE
Add support for generics

### ISSUE THREAD

**Issue by mratsim** [treeform/genny#43]
This fails with "Node is not a symbol" in sym.getImpl

```Nim
import genny

type
  Foo[T] = object
    val: T

proc sum[T](r: var Foo[T], a, b: Foo[T]) =
  r.val = a.val + b.val

exportObject Foo[int]:
  procs:
    sum(Foo[int], Foo[int], Foo[int])

writeFiles("bindings/generated", "test")
include generated/internal
```

https://github.com/treeform/genny/blob/33f0e5a3e6d370c63f11ac0572f6396af684a314/src/genny/languages/nim.nim#L127-L137

**Comment by treeform** [comment]
Genny can't export many of the advanced features of Nim like generics simply because other languages don't support them. There needs to be a tiny simplification layer in your bindings to define concreate functions and concrete types that you do want to export.

```nim
type FooInt = Foo[int]
proc sum(r: FooInt, a, b: FooInt) 
```

And export that instead.

**Comment by mratsim** [comment]
OK, then we run into https://github.com/treeform/genny/issues/44 to handle type aliases
